version: '3'

services: 
  eureka-service:
    build: ./eureka-server
    ports:
      - "8761:8761"
    network_mode: host
  domain-service:
    build: ./domain-service
    ports:
      - "8082:8082"
    network_mode: host
  display-service:
    build: ./display-service
    ports:
      - "8081:8081"
    network_mode: host
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    network_mode: host