version: '3'

services: 
  eureka-service:
    build: ./eureka-server
    ports:
      - "8761:8761"
  domain-service:
    build: ./domain-service
    ports:
      - "8082:8082"
  display-service:
    build: ./display-service
    ports:
      - "8081:8081"





