version: '3'

services: 
  eureka-service:
    build: ./Picon-BackEnd/eureka-server
    ports:
      - "8761:8761"
  domain-service:
    build: ./Picon-BackEnd/domain-service
    ports:
      - "8101:8101"
  display-service:
    build: ./Picon-BackEnd/display-service
    ports:
      - "8102:8102"





