spring:
  application:
    name: zuul
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
server:
  port: 8765
  error:
    include-message: always
zuul:
  routes:
    domain:
      path: /domains/**
      serviceId: domain
      stripPrefix: false
eureka:
  instance:
    non-secure-port: ${server.port}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

