spring:
  application:
    name: zuul
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: validate
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${YAPP_17_RDS_URL}
    username: ${YAPP_17_RDS_USERNAME}
    password: ${YAPP_17_RDS_PASSWORD}
#    url: jdbc:mysql://localhost:3306/db?serverTimezone=UTC&characterEncoding=UTF-8
#    username: root
#    password: password
  main:
    allow-bean-definition-overriding: true
JWT:
  SECRET:
    KEY: ${JWT_SECRET_KEY}
  TOKEN:
    VALIDITY:
      ACCESS: ${JWT_ACCESS_TOKEN_VALIDITY}
      REFRESH: ${JWT_REFRESH_TOKEN_VALIDITY}
server:
  port: 8765
  error:
    include-message: always
zuul:
  routes:
    domain:
      path: /domains/**
      serviceId: domain
      stripPrefix: true
    display:
      path: /displays/**
      serviceId: display
      stripPrefix: false
eureka:
  instance:
    non-secure-port: ${server.port}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
ribbon:
  ConnectTimeout: 5000 # 클라이언트 서버에 연결되는 제한시간
  ReadTimeout: 5000 # 요청에 대한 응답을 받는 제한시간
  MaxTotalHttpConnections: 10000
  MaxConnectionsPerHost: 100