server:
  port: 8081
spring:
  application:
    name: display
eureka:
  instance:
    prefer-ip-address: true # 서비스간 통신 시 hostname 보다 ip 를 우선 사용 - 개발모드
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka # 클라이언트 서버가 등록되는 경로
feign:
  hystrix:
    enabled: true
    command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 5000
    client:
      config:
        default:
          connectTimeout: 5000
          readTimeout: 5000
