server:
  port: 8081
spring:
  application:
    name: display
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
eureka:
  instance:
    prefer-ip-address: true # 서비스간 통신 시 hostname 보다 ip 를 우선 사용 - 개발모드
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka # 클라이언트 서버가 등록되는 경로
ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000
  MaxTotalHttpConnections: 10000
  MaxConnectionsPerHost: 100
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 10000
