server:
  port: 8082
spring:
  application:
    name: domain
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${YAPP_17_RDS_URL}
    username: ${YAPP_17_RDS_USERNAME}
    password: ${YAPP_17_RDS_PASSWORD}
#    url: jdbc:mysql://localhost:3306/db?serverTimezone=UTC&characterEncoding=UTF-8
#    username: root
#    password: password
  cloud:
    refresh:
      enabled: false # jpa hikari HikariDatasource 오류 https://www.python2.net/questions-52486.htm
eureka:
  instance:
    prefer-ip-address: true # 서비스간 통신 시 hostname 보다 ip 를 우선 사용 - 개발모드
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka # 클라이언트 서버가 등록되는 경로


