logging:
  level:
    org.hibernate.type: trace
server:
  port: 8082
spring:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.default_batch_fetch_size: 500
  application:
    name: domain
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${YAPP_17_RDS_URL}
    username: ${YAPP_17_RDS_USERNAME}
    password: ${YAPP_17_RDS_PASSWORD}
#    url: jdbc:mysql://localhost:3306/db?serverTimezone=UTC&characterEncoding=UTF-8
#    username: root
#    password: password
  cloud:
    refresh:
      enabled: false # jpa hikari HikariDatasource 오류 https://www.python2.net/questions-52486.htm
    aws:
      credentials:
        accessKey: ${YAPP_17_S3_ACCESSKEY}
        secretKey: ${YAPP_17_S3_SECRETKEY}
        instanceProfile: true
      s3:
        bucket: yapp-picon
      region:
        static: ap-northeast-2
      stack:
        auto: false
eureka:
  instance:
    prefer-ip-address: true # 서비스간 통신 시 hostname 보다 ip 를 우선 사용 - 개발모드
  client:
    fetchRegistry: true # 레지스터리에 있는 클라이언트 서버목록을 캐시하겠다
    service-url:
      defaultZone: http://localhost:8761/eureka # 클라이언트 서버가 등록되는 경로